[project]
name = "ypricemagic-server"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ypricemagic==5.2.5",
    "fastapi",
    "uvicorn[standard]",
    "diskcache",
]

[tool.uv]
prerelease = "allow"
